version: "3.9"
services:
    mongo:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=openliberty
        ports:
            - "27017:27017"
        volumes:
            -  ~/mongo2/data2:/data/db
            - "./leaderboard/assets/:/docker-entrypoint-initdb.d/"
        command: mongod

    leaderboard:
        build: ./leaderboard
        ports:
            - "9190:9080"
    gameservice:
        build: ./game
        ports:
            - "9070:9080"
        environment:
            - io.openliberty.spacerover.ip=mockrover
            - io.openliberty.spacerover.port=5045
            - io.openliberty.gameboard.ip=mockboard
            - io.openliberty.gameboard.port=5045
    client:
        build:
            context: ./client
            args:
                - GAME_URL=http://localhost:9070/game
                - GAME_SOCKET_URL=ws://localhost:9070/roversocket
                - GAME_DURATION_SECONDS=120
                - LEADERBOARD_URL=http://localhost:9190/mongo/leaderboard
        ports:
            - "3000:80"
    mockrover:
        build: ./mock/rover
        ports:
            - "5045:5045"
    mockboard:
        build: ./mock/board
        ports:
            - "5046:5045"
