{
 "title": "Space Rover Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rover Temperature",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "Temperature (°C)" }
   ]
  }
 ]
}
{
 "title": "Open Liberty Space Rover Mission Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Number of Games Played",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "application_totalNumberOfGames", "legendFormat": "Total number of games" },
    {
     "expr": "application_numberOfSuddenDeathGamesPlayed",
     "legendFormat": "Total number of sudden death games"
    },
    {
     "expr": "application_numberOfClassicGamesPlayed",
     "legendFormat": "Total number of classic games"
    },
    {
     "expr": "application_numberOfPlanetHopGamesPlayed",
     "legendFormat": "Total number of planet hop games"
    },
    {
     "expr": "application_numberOfGuidedGamesPlayed",
     "legendFormat": "Total number of guided games"
    }
   ]
  },
  {
   "title": "Average User Score",
   "type": "graph",
   "description": "The average final score per game played today.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_totalScore/application_totalNumberOfGames",
     "legendFormat": "Score"
    }
   ]
  },
  {
   "title": "Damage Taken Average",
   "type": "graph",
   "description": "The average amount of damage taken during games played today.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_totalDamage / application_totalNumberOfGames",
     "legendFormat": "Damage Average"
    }
   ]
  },
  {
   "title": "Average Game Length",
   "type": "graph",
   "description": "The average time it took to complete a game today.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_timeInGame_seconds/application_totalNumberOfGames",
     "legendFormat": "Game length seconds"
    }
   ]
  },
  {
   "title": "Rover Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Volts" }
   ],
   "targets": [
    { "expr": "application_voltageBattery" }
   ]
  },
  {
   "title": "Space Rover Battery Percentage",
   "type": "graph",
   "description": "The battery level percentage of the space rover. If the space rover isn't reporting the percentage, or is a wired model, this will show 100%. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_pctBatteryLevel_percent",
     "legendFormat": "Battery Percentage"
    }
   ]
  }
 ]
}
{
 "title": "Open Liberty",
 "description": "Created by the Open Liberty observability team",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "base_cpu_processCpuLoad_percent"
   },
   {
    "name": "dur",
    "label": "moving average",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   },
   { "name": "heapUsageThreshold", "label": "Heap Usage Threshold (%)", "query": "10,20,30,40,50,60,70,80,90,100" },
   {
    "name": "garbageCollectionThreshold",
    "label": "Garbage Collection Threshold (%)",
    "query": "10,20,30,40,50,60,70,80,90,100"
   },
   {
    "name": "maxHeapUsageProjection",
    "label": "Max Heap Usage Projection (hours)",
    "query": "1"
   },
   { "name": "cpuDur", "query": "[45s]" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available CPUs",
     "type": "table-old",
     "description": "The total number of CPU threads available to the JVM.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "base_cpu_availableProcessors{instance=~\"${instance}\"}",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Process CPU Time",
     "type": "graph",
     "description": "The portion of CPU available to each Liberty instance that has been used within the last ${dur} on average.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(base_cpu_processCpuTime_seconds{instance=~\"${instance}\"} ${cpuDur}) / base_cpu_availableProcessors",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU System Load",
     "type": "graph",
     "description": "For CPUs Liberty is running on, the average number of runnable entities that have been scheduled or executed by the system, over the last minute.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_cpu_systemLoadAverage{instance=~\"${instance}\"}",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instances Above [$heapUsageThreshold%] Heap Usage",
     "type": "table-old",
     "description": "Instances that are currently utilizing more than [$heapUsageThreshold%] of their configured maximum heap size.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{instance=~\"${instance}\"} / base_memory_maxHeap_bytes{instance=~\"${instance}\"} > ${heapUsageThreshold}/100"
      }
     ]
    },
    {
     "title": "Increasing Heap Usage Trend Based on Last ${dur}",
     "type": "table-old",
     "description": "Instances with an increase in heap usage within the last ${dur}.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "deriv(base_memory_usedHeap_bytes{instance=~\"${instance}\"}${dur}) > 0"
      }
     ]
    },
    {
     "title": "Servers That May Reach Max Heap Usage Within [$maxHeapUsageProjection hour(s)] Based on Last ${dur}",
     "type": "table-old",
     "description": "Instances projected to reach their maximum heap size within [$maxHeapUsageProjection hour(s)] based on  data over the last ${dur}.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "predict_linear(base_memory_usedHeap_bytes{instance=~\"${instance}\"}${dur}, $maxHeapUsageProjection * 3600) > base_memory_maxHeap_bytes{instance=~\"${instance}\"}"
      }
     ]
    },
    {
     "title": "Configured Maximum Heap Size",
     "type": "table-old",
     "description": "An instance's maximum heap size.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "base_memory_maxHeap_bytes{instance=~\"${instance}\"}"
      }
     ]
    },
    {
     "title": "Heap Usage Percentage",
     "type": "graph",
     "description": "The percentage of heap memory currently in use.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{instance=~\"${instance}\"} / base_memory_maxHeap_bytes{instance=~\"${instance}\"}",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slowest REST Resources Over Last ${dur} by Average Response Time",
     "type": "table-old",
     "description": "The average response time for requests made to a particular REST resource, across all servers, based on data over the last ${dur}.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "avg(rate(base_REST_request_elapsedTime_seconds{instance=~\"${instance}\"}${dur}) / rate(base_REST_request_total{instance=~\"${instance}\"}${dur})) by (class, method) > 0",
       "legendFormat": "instance: {{instance}}, class: {{class}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "REST Request Count Over Last ${dur}",
     "type": "graph",
     "description": "The number of visits made to a REST resource instance within the past ${dur}.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(base_REST_request_total{instance=~\"${instance}\"}${dur})",
       "legendFormat": "instance: {{instance}}, class: {{class}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Average Response Time per REST Request Over Last ${dur} ",
     "type": "graph",
     "description": "The average response time for a request made to a REST resource instance, based on data over the last ${dur}.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_REST_request_elapsedTime_seconds{instance=~\"${instance}\"}${dur}) / rate(base_REST_request_total{instance=~\"${instance}\"}${dur})",
       "legendFormat": "instance: {{instance}}, class: {{class}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Request Count by REST Resource Over Last ${dur}",
     "type": "graph",
     "description": "The sum of visits to a particular REST resource over all servers, based on data over the last ${dur}.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(base_REST_request_total{instance=~\"${instance}\"}${dur})) by (class, method)",
       "legendFormat": "class: {{class}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Request Over Last ${dur} by REST Resource",
     "type": "graph",
     "description": "The average response time for requests made to a particular REST resource method, across all servers, based on data over the last ${dur}.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(base_REST_request_elapsedTime_seconds{instance=~\"${instance}\"}${dur}) / rate(base_REST_request_total{instance=~\"${instance}\"}${dur})) by (class, method)",
       "legendFormat": "class: {{class}}, method: {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fault Tolerance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failure Rate Over Last $dur Aggregated Over $instance Instance(s)",
     "type": "graph",
     "description": "Percentage of calls which resulted in a failure.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_invocations_total{instance=~'$instance', result='exceptionThrown'}${dur})) * 100 \n/ \nsum by (method)(rate(base_ft_invocations_total{instance=~'$instance'}${dur}))",
       "legendFormat": "method: {{method}}"
      }
     ]
    },
    {
     "title": "Top 5 Most Frequently Failing Methods Over Last $dur",
     "type": "table-old",
     "description": "Percentage of calls which resulted in a failure.\n\nThis graph is showing failures after all fault tolerance processing has taken place (including fallback)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "topk(5, \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~'$instance', result='exceptionThrown'}${dur})) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~'$instance'}${dur})) \n) \n> 0 "
      }
     ]
    },
    {
     "title": "Fallback Rate Over Last $dur Aggregated Over $instance Instance(s)",
     "type": "graph",
     "description": "Percentage of method invocations which resulted in the fallback method or handler being called over the past $dur.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_invocations_total{instance=~'$instance', fallback='applied'}${dur})) * 100 \n/ \nsum by (method)(rate(base_ft_invocations_total{instance=~'$instance'}${dur}))",
       "legendFormat": "method: {{method}}"
      }
     ]
    },
    {
     "title": "Top 5 Methods Most Frequently Applying Fallback Over Last $dur",
     "type": "table-old",
     "description": "Percentage of calls which resulted in the Fallback method or handler being called over the last $dur",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "topk(5, \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~'$instance', fallback='applied'}${dur})) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~'$instance'}${dur})) \n) \n> 0 "
      }
     ]
    },
    {
     "title": "Retried Rate Over Last $dur Aggregated Over $instance Instance(s)",
     "type": "graph",
     "description": "Percentage of method invocation which retried at least once over the last $dur.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_retry_calls_total{instance=~'$instance', retried='true'}${dur})*100)\n/\nsum by (method)(rate(base_ft_retry_calls_total{instance=~'$instance'}${dur}))",
       "legendFormat": "method: {{method}}"
      }
     ]
    },
    {
     "title": "Top 5 Methods Most Frequently Applying A Retry Over Last $dur",
     "type": "table-old",
     "description": "Percentage of calls which apply at least one Retry over the last $dur.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "topk(5, \nsum without (retried, retryResult)(rate(base_ft_retry_calls_total{instance=~'$instance', retried='true'}${dur})) * 100 \n/ \nsum without (retried, retryResult)(rate(base_ft_retry_calls_total{instance=~'$instance'}${dur})) \n) \n> 0 "
      }
     ]
    }
   ]
  },
  {
   "title": "Servlets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slowest Servlets Over Last ${dur} by Average Response Time",
     "type": "table-old",
     "description": "The average response time for requests made to a particular servlet, across all servers, based on data over the last ${dur}.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "avg(rate(vendor_servlet_responseTime_total_seconds{instance=~\"${instance}\"}${dur}) / rate(vendor_servlet_request_total{instance=~\"${instance}\"}${dur})) by (servlet) > 0"
      }
     ]
    },
    {
     "title": "Request Count Over Last ${dur}",
     "type": "graph",
     "description": "The number of visits made to a servlet instance within the past ${dur}.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(vendor_servlet_request_total{instance=~\"${instance}\"}${dur})",
       "legendFormat": "instance: {{instance}}, servlet: {{servlet}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Request Over Last ${dur} ",
     "type": "graph",
     "description": "The average response time for a request made to a servlet instance, based on data over the last ${dur}.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_servlet_responseTime_total_seconds{instance=~\"${instance}\"}${dur})/rate(vendor_servlet_request_total{instance=~\"${instance}\"}${dur})",
       "legendFormat": "instance: {{instance}}, servlet: {{servlet}}"
      }
     ]
    },
    {
     "title": "Request Count by Servlet Over Last ${dur}",
     "type": "graph",
     "description": "The sum of visits to a particular servlet over all servers, based on data over the last ${dur}.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(vendor_servlet_request_total{instance=~\"${instance}\"}${dur})) by (servlet)",
       "legendFormat": "servlet: {{servlet}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Request Over Last ${dur} by Servlet",
     "type": "graph",
     "description": "The average response time for requests made to a particular servlet, across all servers, based on data over the last ${dur}.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vendor_servlet_responseTime_total_seconds{instance=~\"${instance}\"}${dur}) / rate(vendor_servlet_request_total{instance=~\"${instance}\"}${dur})) by (servlet)",
       "legendFormat": "servlet: {{servlet}}"
      }
     ]
    },
    {
     "title": "Currently Slow Requests",
     "type": "graph",
     "description": "The number of servlet requests that are currently running but are slow.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_requestTiming_slowRequestCount",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Currently Hung Requests",
     "type": "graph",
     "description": "The number of servlet requests that are currently running but are hung.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_requestTiming_hungRequestCount",
       "legendFormat": "instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Used Over Last ${dur}",
     "type": "table-old",
     "description": "The total number of connection requests that were used over the last ${dur}. Any connections that are currently in use are not included in this total.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "increase(vendor_connectionpool_usedConnections_total{instance=~\"${instance}\"}${dur}) > 0"
      }
     ]
    },
    {
     "title": "Connection Requests Queued Over Last ${dur}",
     "type": "table-old",
     "description": "The total number of connection requests that waited for a connection because of a full connection pool over the last ${dur}.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "increase(vendor_connectionpool_queuedRequests_total{instance=~\"${instance}\"}${dur}) > 0"
      }
     ]
    },
    {
     "title": "Average Time Usage per Connection Over Last ${dur}",
     "type": "graph",
     "description": "The average time any used connection was put in use, based on data over the last ${dur}.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_inUseTime_total_seconds{instance=~\"${instance}\"}${dur}) / rate(vendor_connectionpool_usedConnections_total{instance=~\"${instance}\"}${dur}) > 0",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Average Wait Time per Queued Connection Request Over Last ${dur}",
     "type": "graph",
     "description": "The average wait time for any queued connection request, based on data over the last ${dur}.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_waitTime_total_seconds{instance=~\"${instance}\"}${dur}) / rate(vendor_connectionpool_queuedRequests_total{instance=~\"${instance}\"}${dur}) > 0",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Managed Connections",
     "type": "graph",
     "description": "The sum of managed connections in the free, shared, and unshared pools.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_managedConnections{instance=~\"${instance}\"}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Free Connections",
     "type": "graph",
     "description": "The number of managed connections in the free pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_freeConnections{instance=~\"${instance}\"}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Connection Handles",
     "type": "graph",
     "description": "The number of connections that are in use. This number might include multiple connections that are shared from a single managed connection.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_connectionHandles{instance=~\"${instance}\"}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Create Total",
     "type": "graph",
     "description": "The total number of managed connections created since the pool was created.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_create_total{instance=~\"${instance}\"}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Destroy Total",
     "type": "graph",
     "description": "The total number of managed connections destroyed since the pool was created.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_destroy_total{instance=~\"${instance}\"}",
       "legendFormat": "datasource: {{datasource}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "graph",
     "description": "A session is considered active if the application server is processing a request that uses that user session.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_activeSessions{instance=~\"${instance}\"}",
       "legendFormat": "appname: {{appname}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Live  Sessions",
     "type": "graph",
     "description": "A session is considered live if the session is loaded into memory by the application server.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_liveSessions{instance=~\"${instance}\"}",
       "legendFormat": "appname: {{appname}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threadpools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Largest Threadpool Sizes Over Last ${dur}",
     "type": "table-old",
     "description": "The size of the Default Executor thread pool in each instance, based on data over the last ${dur}.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "max_over_time(vendor_threadpool_size{instance=~\"${instance}\"}${dur})"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "description": "The number of threads that are actively running tasks.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_activeThreads{instance=~\"${instance}\"}",
       "legendFormat": "pool: {{pool}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Threadpool Size",
     "type": "graph",
     "description": "The size of the Default Executor thread pool in each instance.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_size{instance=~\"${instance}\"}",
       "legendFormat": "pool: {{pool}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instances With > [$garbageCollectionThreshold]% of Time Spent Garbage Collecting During Last ${dur}",
     "type": "table-old",
     "description": "Instances that spent more than [$garbageCollectionThreshold%] of the time garbage collecting, during the last ${dur}.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum (rate(base_gc_time_seconds{instance=~\"${instance}\"}${dur})) by (instance) > ${garbageCollectionThreshold} / 100"
      }
     ]
    },
    {
     "title": "Most Time Spent on Garbage Collection Over Last ${dur}",
     "type": "table-old",
     "description": "The portion of time an instance spent on a specific type of garbage collection, based on data over the last ${dur}. ",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{instance=~\"${instance}\"}${dur}) > 0"
      }
     ]
    },
    {
     "title": "Time per Garbage Collection Cycle ${dur} moving average",
     "type": "graph",
     "description": "The average time an instance took on a specific type of garbage collection, based on data over the last ${dur}.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{instance=~\"${instance}\"}${dur}) / rate(base_gc_total{instance=~\"${instance}\"}${dur})",
       "legendFormat": "instance: {{instance}} name: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other JVM Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Uptime",
     "type": "table-old",
     "description": "The time elapsed since the start of the JVM.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "base_jvm_uptime_seconds{instance=~\"${instance}\"}"
      }
     ]
    }
   ]
  }
 ]
}