apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
  namespace: spacerover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
      - name: board
        image: ayadinou/board:latest
        ports:
        - containerPort: 5045

---
apiVersion: v1
kind: Service
metadata:
  name: board
  namespace: spacerover
spec:
  selector:
    app: board
  ports:
    - protocol: TCP
      port: 5045
      targetPort: 5045
  type: ClusterIP

