apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spacerover-service-monitor
  namespace: observability
spec:
  endpoints:
    - interval: 15s
      port: metrics
      scrapeTimeout: 14s
  namespaceSelector: 
    matchNames:
      - spacerover
  selector:
    matchLabels:
      app.kubernetes.io/part-of: gameservice
